### PR TITLE
FEAT: Server is live

### PR DESCRIPTION
**Pull request by Jsyrett977**

### CODE REVIEW

**Review by ReleventGull — COMMENTED** [review]
Looks gooooooooood

**Review by propurty — APPROVED** [review]
Looks great!

**Review by ReleventGull — COMMENTED** [review]
Good fix :)

**Review by cusmoritz — APPROVED** [review]
Looks good. Should we be writing down the functions that we 'create', like it api/index.js line 11? Or is that something we care about

**Pull request merged**
