### PR TITLE
React foundation and template code to work off of

### LINKED ISSUE #23: Create React front end
As a user, I want to be able to use the urls.

Routes
- /
- /login
- /register
- /me (maybe cart / change user info)
- /products (all products)
- /products/:productId (details page)

App.js
Header.js
Footer.js

### PR DESCRIPTION
**Pull request by propurty**
I setup skeleton components that we can change however we want. I also setup a CSS file to go with semantic, they are only for temporary testing. I did not push 5 other potential components since I do not know what other work has been done so far on them. We may also use createBrowserRouter instead, I just didn't have the time to research it. BrowserRouter will work fine for now.

### CODE REVIEW

**Comment by propurty** [comment]
I did actually have a good skeleton component for our accounts feature, but we can talk about it later since Justin has account related components already. I also have a few things for Cards, CardDetail, and CardItem. But again, I will wait till later to see what has already been done.

**Comment by propurty** [comment]
I'll also change the CSS to fit our components after we get more of the components merged.

**Review by cusmoritz — APPROVED** [review]
Solid front end

**Review by ReleventGull — COMMENTED** [review]
Gorgeous

**Review by ReleventGull — APPROVED** [review]

**Pull request merged**
